
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EasyHousingSolutions_Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Buyer
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Buyer()
    {

        this.Carts = new HashSet<Cart>();

    }


    public int BuyerId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public System.DateTime DateOfBirth { get; set; }

    public string PhoneNo { get; set; }

    public string EmailId { get; set; }

    public string User_Name { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Cart> Carts { get; set; }

}

}
