
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EasyHousingSolutions_Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Property
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Property()
    {

        this.Carts = new HashSet<Cart>();

        this.Images = new HashSet<Image>();

    }


    public int PropertyId { get; set; }

    public string PropertyName { get; set; }

    public string PropertyType { get; set; }

    public string PropertyOption { get; set; }

    public string Description { get; set; }

    public string Address { get; set; }

    public decimal PriceRange { get; set; }

    public decimal InitialDeposit { get; set; }

    public string Landmark { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public int SellerId { get; set; }

    public int CityId { get; set; }

    public int StateId { get; set; }

    public string Status_Description { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Cart> Carts { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Image> Images { get; set; }

    public virtual Seller Seller { get; set; }

    public virtual City City { get; set; }

    public virtual State State { get; set; }

}

}
